/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2025 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-x86_64-clang"
#define DATE "built on: Sun Jun 28 09:23:15 2026 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','/','h','o','m','e','/',
    'l','x','h','/','P','r','o','j','e','c','t','s','/','N','S','P',
    'A','/','w','o','r','k','s','p','a','c','e','/','o','p','e','n',
    's','s','l','-','b','c','/','w','r','a','p','p','e','r','s','/',
    'c','l','a','n','g','-','b','c',' ','-','f','P','I','C',' ','-',
    'p','t','h','r','e','a','d',' ','-','m','6','4',' ','-','O','0',
    ' ','-','g',' ','-','D','L','_','E','N','D','I','A','N',' ','-',
    'D','O','P','E','N','S','S','L','_','P','I','C','\0'
};
